name: Publish to GitHub Packages
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      TIMESTAMP: $(date +'%Y%m%d%H%M%S')
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/onedemo:${{ github.sha }}-${{ env.TIMESTAMP }}